#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: sidecar-monitor-scripts
#  namespace: monitoring-sidecar
#data:
#  myCustomScript.sh: |
    #!/bin/bash
    
#    IP=${IP:=127.0.0.1}
#    PORT=${PORT:=8091}
#    QUERY_PORT=${QUERY_PORT:=8093}
    
#    USERNAME=${USERNAME:="Administrator"}
#    PASSWORD=${PASSWORD:="password"}
    
#    N1QL_STMT='SELECT name FROM `travel-sample`.inventory.hotel LIMIT 1'
    
#    i=1
#    numbered_echo() {
#      echo "[$i] $@"
#      i=$(expr $i + 1)
#    }

#    # Check if couchbase server is up
#    check_db() {
#      curl --silent --output /dev/null http://$IP:$PORT
#      echo $?
#    }
    
#    SUCCESS_CODE=200
#    EXIT_CODE=0
#    response=""
#    # Issue POST and extract response
#    launch_query() {
      # final_cmd="curl --silent $QUERY"
#      numbered_echo "curl --write-out %{http_code} --output /dev/null --silent -u $USERNAME:$PASSWORD http://$IP:$QUERY_PORT/query/service -d \"statement=$N1QL_STMT\""
#      response=$(curl --write-out %{http_code} --output /dev/null --silent -u $USERNAME:$PASSWORD http://$IP:$QUERY_PORT/query/service -d "statement=$N1QL_STMT")
#      echo $response
#      if [ $response -ne $SUCCESS_CODE ]
#      then
#        EXIT_CODE=1
#        echo "Received: $response Expected: $SUCCESS_CODE => Exiting with exit code: $EXIT_CODE"
#        exit $EXIT_CODE
#      fi
#    }

#    # Wait untl cb db is ready
#    until [[ $(check_db) = 0 ]]; do
#      numbered_echo "cb db not available yet"
#      sleep 1
#    done
    
#    numbered_echo "cb db is available"
    
#    # LAUNCH QUERY
#    launch_query
    
#   exit $EXIT_CODE

#  myStupidScript.sh: |
#    #!/bin/bash
    
#    echo "I am alive and starting"
    
#    sleep 45
    
#    echo "I am still alive after 45 seconds"