apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-monitor-env-vars
  namespace: monitoring-sidecar
data:
  # SCAN_FREQUENCY="@every 15s"
  # PROBE_TIMEOUT="300" # 300 ms
  LOG_LEVEL: "debug"
  LOG_FORMAT: "json"

  NODE_NAME: "pg-proxy"
  HOST_CLUSTER_ID: "host-cluster-id"
  INSTANCE_ID: "instance-id"
  RESOURCE_ID: "resource-id"
  
  SCRIPTS_MOUNT_PATH: "/etc/monitoring/scripts/"
  CUSTOM_HEALTH_PROBE_NAMES: "myCustomScript.sh,myStupidScript.sh"

  VECTOR_ENDPOINT_ENABLED: "false"
  
  DEFAULT_HEALTH_PROBE_TARGET_PROCESS_NAMES: "runsv,indexer"
  DEFAULT_HEALTH_PROBE_TARGET_ENDPOINTS: "http://localhost:12323/healthz"
  SIDECAR_HEALTHZ_SERVER_PORT: "5432"  